"""Learned inline-link discovery: mention detection plus closed-world linking.

This subsystem implements SPEC-INLINE-LINKING.md: a staged span-proposal ->
naturalness -> retrieval -> rerank -> calibrated-rejection pipeline over the
existing linkdiscovery contracts. The package ships the data records shared
by every stage; the data-audit tooling (sampling, annotation, agreement,
tiering) that gates all modeling; the anchor dictionary and span-proposal
stages; the frozen-encoder representations, heads, training, and calibration
of Architecture A; the deterministic baseline engine and global selection;
the evaluation suite; and the :mod:`~linkdiscovery.inline.workflow`
orchestration layer plus :mod:`~linkdiscovery.inline.report` review outputs
that wire it all together behind the ``linkdiscovery inline`` CLI.
"""

from linkdiscovery.inline.anchors import (
    AnchorConfig,
    AnchorDictionary,
    build_anchor_dictionary,
    mention_pattern,
    normalize_mention,
)
from linkdiscovery.inline.audit import (
    GRAPH_ONLY_REGIONS,
    agreement_report,
    build_audit_report,
    build_audit_sample,
    cohen_kappa,
    derive_tier,
    krippendorff_alpha,
    load_audit_labels,
    run_annotation_session,
    save_audit_labels,
)
from linkdiscovery.inline.baseline import (
    BaselineConfig,
    levenshtein_ratio,
    propose_baseline,
    score_baseline,
)
from linkdiscovery.inline.calibrate import (
    ConformalAbstainer,
    apply_temperature,
    expected_calibration_error,
    fit_temperature,
    reliability_table,
)
from linkdiscovery.inline.encode import (
    WIDTH_BUCKET_COUNT,
    HashingTokenEncoder,
    QwenTokenEncoder,
    TokenStateEncoder,
    TokenStates,
    span_representation,
    span_representation_dim,
)
from linkdiscovery.inline.evaluate import (
    SplitAssignment,
    bpref,
    judged_only_precision,
    kill_criterion,
    operating_point,
    retrieval_metrics,
    score_benchmark,
    span_detection_f1,
    three_way_split,
)
from linkdiscovery.inline.heads import (
    NaturalnessConfig,
    RerankerConfig,
    RetrievalConfig,
    TrainedHeads,
    build_naturalness_head,
    build_pair_features,
    build_reranker_head,
    build_retrieval_head,
    reranker_input_dim,
    retrieval_logits,
)
from linkdiscovery.inline.records import (
    PRODUCER_VERSION,
    SCHEMA_VERSION,
    AuditItem,
    AuditLabel,
    AuditReport,
    AuditSample,
    Benchmark,
    BenchmarkCase,
    BenchmarkKind,
    InlineProposal,
    InlineProposalSet,
    LinkRegionKind,
    SpanCandidate,
    Tier,
)
from linkdiscovery.inline.report import write_inline_report
from linkdiscovery.inline.select import (
    SelectionConfig,
    combine_scores,
    precision_recall_sweep,
    select_proposals,
)
from linkdiscovery.inline.spans import SpanConfig, propose_spans, span_recall
from linkdiscovery.inline.train import (
    DEFAULT_PAIR_FEATURE_NAMES,
    SpanRepTable,
    TargetCatalog,
    TrainConfig,
    TrainingData,
    TrainingExample,
    build_training_data,
    confirmed_negative_mask,
    default_pair_hand_features,
    mine_hard_negatives,
    naturalness_training_arrays,
    reranker_positive_examples,
    retrieval_training_arrays,
    train_heads,
)
from linkdiscovery.inline.workflow import (
    INLINE_FEATURE_NAMES,
    InlineInputs,
    build_anchor_artifacts,
    build_audit_artifacts,
    check_span_recall,
    load_audit_sample,
    load_inline_inputs,
    propose_inline_baseline,
    propose_inline_learned,
    train_inline_heads,
)

__all__ = [
    "DEFAULT_PAIR_FEATURE_NAMES",
    "GRAPH_ONLY_REGIONS",
    "INLINE_FEATURE_NAMES",
    "PRODUCER_VERSION",
    "SCHEMA_VERSION",
    "WIDTH_BUCKET_COUNT",
    "AnchorConfig",
    "AnchorDictionary",
    "AuditItem",
    "AuditLabel",
    "AuditReport",
    "AuditSample",
    "BaselineConfig",
    "Benchmark",
    "BenchmarkCase",
    "BenchmarkKind",
    "ConformalAbstainer",
    "HashingTokenEncoder",
    "InlineInputs",
    "InlineProposal",
    "InlineProposalSet",
    "LinkRegionKind",
    "NaturalnessConfig",
    "QwenTokenEncoder",
    "RerankerConfig",
    "RetrievalConfig",
    "SelectionConfig",
    "SpanCandidate",
    "SpanConfig",
    "SpanRepTable",
    "SplitAssignment",
    "TargetCatalog",
    "Tier",
    "TokenStateEncoder",
    "TokenStates",
    "TrainConfig",
    "TrainedHeads",
    "TrainingData",
    "TrainingExample",
    "agreement_report",
    "apply_temperature",
    "bpref",
    "build_anchor_artifacts",
    "build_anchor_dictionary",
    "build_audit_artifacts",
    "build_audit_report",
    "build_audit_sample",
    "build_naturalness_head",
    "build_pair_features",
    "build_reranker_head",
    "build_retrieval_head",
    "build_training_data",
    "check_span_recall",
    "cohen_kappa",
    "combine_scores",
    "confirmed_negative_mask",
    "default_pair_hand_features",
    "derive_tier",
    "expected_calibration_error",
    "fit_temperature",
    "judged_only_precision",
    "kill_criterion",
    "krippendorff_alpha",
    "levenshtein_ratio",
    "load_audit_labels",
    "load_audit_sample",
    "load_inline_inputs",
    "mention_pattern",
    "mine_hard_negatives",
    "naturalness_training_arrays",
    "normalize_mention",
    "operating_point",
    "precision_recall_sweep",
    "propose_baseline",
    "propose_inline_baseline",
    "propose_inline_learned",
    "propose_spans",
    "reliability_table",
    "reranker_input_dim",
    "reranker_positive_examples",
    "retrieval_logits",
    "retrieval_metrics",
    "retrieval_training_arrays",
    "run_annotation_session",
    "save_audit_labels",
    "score_baseline",
    "score_benchmark",
    "select_proposals",
    "span_detection_f1",
    "span_recall",
    "span_representation",
    "span_representation_dim",
    "three_way_split",
    "train_heads",
    "train_inline_heads",
    "write_inline_report",
]
